project:
  name: 'TerraHub_CLI'
  code: '59d5adf8'
  provider: 'aws'

terraform:
  varFile:
    - 'default.tfvars'
  workspace:
    dev:
      varFile:
        - 'workspace/dev.tfvars'
    prod:
      varFile:
        - 'workspace/prod.tfvars'
